<?php

namespace Database\Seeders;

// use App\Models\Craft;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CraftsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('crafts')->delete();

        $crafts = [
            [
                'name' => 'Babysitter',
                'slug' => 'babysitter',
                'icon' => 'baby-carriage',
                'synonyms' => 'Au pair, nanny',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Barber',
                'slug' => 'barber',
                'icon' => 'scissors',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Beautician',
                'slug' => 'beautician',
                'icon' => 'paintbrush-fine',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Carpenter',
                'slug' => 'carpenter',
                'icon' => 'hammer',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Carpet cleaner',
                'slug' => 'carpet-cleaner',
                'icon' => 'rug',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Electrician',
                'slug' => 'electrician',
                'icon' => 'lightbulb',
                'synonyms' => '',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Gardener',
                'slug' => 'gardener',
                'icon' => 'trowel',
                'synonyms' => '',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Glass repair technician',
                'slug' => 'glass-repair-technician',
                'icon' => 'wine-glass-crack',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Glazier',
                'slug' => 'glazier',
                'icon' => 'window-frame',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Hairdresser',
                'slug' => 'hairdresser',
                'icon' => 'scissors',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Handyman',
                'slug' => 'handyman',
                'icon' => 'screwdriver',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'HVAC technician',
                'slug' => 'hvac-technician',
                'icon' => 'air-conditioner',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Ironworker',
                'slug' => 'ironworker',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Jewelry maker',
                'slug' => 'jewelry-maker',
                'icon' => 'rings-wedding',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Landscaper',
                'slug' => 'landscaper',
                'icon' => 'trowel',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Locksmith',
                'slug' => 'locksmith',
                'icon' => 'key-skeleton-left-right',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Maid',
                'slug' => 'maid',
                'icon' => 'broom',
                'synonyms' => 'cleaner, housekeeper',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Makeup artist',
                'slug' => 'makeup-artist',
                'icon' => 'paintbrush-fine',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Massage therapist',
                'slug' => 'massage-therapist',
                'icon' => 'spa',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Mechanic',
                'slug' => 'mechanic',
                'icon' => 'car-wrench',
                'synonyms' => '',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Painter',
                'slug' => 'painter',
                'icon' => 'paint-roller',
                'synonyms' => '',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Pest control specialist',
                'slug' => 'pest-control-specialist',
                'icon' => 'ban-bug',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Plasterer',
                'slug' => 'plasterer',
                'icon' => 'trowel',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Plumber',
                'slug' => 'plumber',
                'icon' => 'toilet',
                'synonyms' => '',
                'priority' => 3,
                'img' => '',
            ],
            [
                'name' => 'Pool cleaner',
                'slug' => 'pool-cleaner',
                'icon' => 'water-ladder',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Potter',
                'slug' => 'potter',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Roofer',
                'slug' => 'roofer',
                'icon' => '',
                'synonyms' => 'xogħol ta\' membrane ',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Sheet metal worker',
                'slug' => 'sheet-metal-worker',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Skin care specialist',
                'slug' => 'skin-care-specialist',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Speech therapist',
                'slug' => 'speech-therapist',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Textile artist',
                'slug' => 'textile-artist',
                'icon' => '',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            [
                'name' => 'Tile installer',
                'slug' => 'tile-installer',
                'icon' => 'grid-2',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Upholsterer',
                'slug' => 'upholsterer',
                'icon' => 'couch',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Welder',
                'slug' => 'welder',
                'icon' => '',
                'synonyms' => '',
                'priority' => 2,
                'img' => '',
            ],
            [
                'name' => 'Window cleaner',
                'slug' => 'window-cleaner',
                'icon' => 'blinds-open',
                'synonyms' => '',
                'priority' => 1,
                'img' => '',
            ],
            
        ];

        DB::table('crafts')->insert($crafts);
    }
}
